spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/dh
        registration:
          keycloak:
            provider: keycloak
            client-id: api-gateway-client
            client-secret: dmEiz0iSHaBdeRA5gZBvyBwmgAAeUrpX
            authorization-grant-type: client_credentials
            redirect-uri: http://localhost:9090/login/oauth2/code/keycloak
            scope: openid, profile, email

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Origin
              - X-Requested-With
              - Content-Type
              - Accept
              - Authorization
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: user-service
          uri: http://user-service:8087
          predicates:
            - Path=/users/**
        - id: accounts-service
          uri: http://accounts-service:8083
          predicates:
            - Path=/accounts/**

    config:
      uri: http://config-service:8889/
      discovery:
        serviceId: config-service
      enabled: false

  application:
    name: gateway-service

  config:
    import: "optional:configserver:"

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true

info:
  app:
    name: Gateway
    description: API gateway
    version: 1.0.0

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: http://localhost:8085/actuator/info
    healthCheckUrlPath: http://localhost:8085/actuator/info
  #client:
    #serviceUrl:
     # defaultZone: http://eureka-server:8761/eureka/

server:
  port: 8085

