spring:
  zipkin:
    enabled: false
  application:
    name: gateway-service
  cloud:
    config:
      discovery:
        serviceId: config-server
        enabled: true
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: checkout-service
          uri: lb://checkout-service
          predicates:
            - Path=/checkout/**
          filters:
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Red, Blue
        - id: product-service
          uri: lb://products-service
          predicates:
            - Path=/products/**
        - id: user-service
          uri: http://localhost:8087
          predicates:
            - Path=/users/**

server:
  port: 8085


