spring:
  application:
    name: gateway-service
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/dh
        registration:
          keycloak:
            provider: keycloak
            client-id: api-gateway-client
            client-secret: dmEiz0iSHaBdeRA5gZBvyBwmgAAeUrpX
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9090/login/oauth2/code/keycloak
            scope: openid, profile, email
      #resourceserver:
        #jwt:
          #issuer-uri: http://keycloak:8080/realms/dh
  
  cloud:
    config:
      discovery:
        serviceId: config-server
        enabled: true
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: checkout-service
          uri: lb://checkout-service
          predicates:
            - Path=/checkout/**
          filters:
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Red, Blue
        - id: product-service
          uri: lb://products-service
          predicates:
            - Path=/products/**
        - id: user-register
          uri: lb://user-register
          predicates:
            - Path=/user/**
server:
  port: 8085
management:
  tracing:
    sampling:
      probability: 1.0
# eureka:
  # client:
    # serviceUrl:
      # defaultZone: http://eureka-server:8761/eureka/
